### ISSUE TITLE
Was killing Qt4 support necessary?

### ISSUE THREAD

**Issue by barracuda156** [quazaa-development-team/Quazaa#1]
The commit removing Qt4 support https://github.com/quazaa-development-team/Quazaa/commit/95eb80d7029bb65daa0178cdaa0c85904bf30067 reverts cleanly, so apparently nothing has been changed since then. What was the point to remove it?

**Comment by josephcrowell** [comment]
IIRC it was for performance and staying up to date with actively developed and supported libraries. The project has been dead for 11 years and this commit is older than that though. Feel free to fork and continue development if you want an application for a dead (and unencrypted) P2P network that no one uses any more.

**Comment by barracuda156** [comment]
Thank you for responding.

`gtk-gnutella` is broken, I could not trace the bug so far, so looked for a replacement app :)

**Comment by barracuda156** [comment]
BTW, what happened to this branch? https://github.com/quazaa-development-team/Quazaa/commits/HostCache
Apparently did not get merged into master, despite having quite a number of newer commits.

**Comment by josephcrowell** [comment]
https://shareaza.sourceforge.net/

**Comment by josephcrowell** [comment]
We stopped development on Quazaa around the time that Limewire got sued. It never transferred a file.

**Comment by barracuda156** [comment]
> We stopped development on Quazaa around the time that Limewire got sued. It never transferred a file.

Oh wow. Got it. Limewire was a nice app.

P. S. `Shareaza` is Windows-only, if I don’t mistake. You seem to have been the only Unix alternative.

**Comment by josephcrowell** [comment]
Shareaza runs well in Wine.

**Comment by barracuda156** [comment]
> Shareaza runs well in Wine.

And Wine is x86-only 😐

P. S. In fact it’s a bit surprising that Shareaza wasn’t ported or an alternative didn’t emerge, but what can we do.

**Comment by josephcrowell** [comment]
I was a member of the Shareaza team and this was the port. Unfortunately the network died due to poisoning from the RIAA and also continual legal attacks. Plus better alternatives emerged such as torrents. In the end, yes: What can we do.
